### ISSUE TITLE
Add response size metric

### ISSUE THREAD

**Issue by bjfletcher** [Financial-Times/next-metrics#100]
The objective is to understand better the performance of the stream app.  One way of doing this is to measure the response sizes of fetches done by the stream app.

@commuterjoy suggested adding fetch response size as a metric to be graphed on Graphite. @matthew-andrews suggested this can be done through adding the `content-length` header into the metrics.

**Comment by commuterjoy** [comment]
nb. would need to be a histogram type metric rather than a simple counter
