### ISSUE TITLE
mitm pinned to 1.2.0 due to failing tests

### ISSUE THREAD

**Issue by GlynnPhillips** [Financial-Times/next-metrics#111]
The recent [mitm 1.2.1](https://github.com/moll/node-mitm/blob/master/CHANGELOG.md#121-mar-30-2016) change has caused the tests to fail due to the socket 'data' event not being called.

For now I have pinned `mitm` to `1.2.0` so deployments pass but this should be looked at soon so we don't get stuck on dev dependencies.

Here is the test that failed on `1.2.1` https://github.com/Financial-Times/next-metrics/blob/master/tests/client.spec.js#L25

**Comment by rowanmanning** [comment]
We're not gonna get to this before deprecating this system
