### ISSUE TITLE
Allow us to graph individual response codes

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/next-metrics#27]
Log both the status class (Eg, 3xx) and the individual codes 301, 302, 304 etc. This will give us greater visibility over the application behaviour.

**Comment by wheresrhys** [comment]
Done. We need to move all our monitoring off `express.http.res.status_2XX` and onto `express.default_route.status.200` style metrics then the old method can be removed https://github.com/Financial-Times/next-metrics/blob/master/lib/metrics.js#L145 @matthew-andrews

**Comment by matthew-andrews** [comment]
i think this is done now
