### ISSUE TITLE
Intercept at HTTP layer

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/next-metrics#287]
Currently we are instrumenting the globally available fetch method ([added by n-express][1]) to record response times of outgoing HTTP requests. However, we don't always get to use fetch - API specific SDKs, or client libraries may bring or implement their own code, meaning we have blind spots.

Perhaps we should look into augmenting Node's HTTP library directly, for example [as done by nock][2], to ensure that we capture this extra information.

[1]: https://github.com/Financial-Times/n-express/blob/c3bf6fda0819c501b62dde408aba8726adae6197/main.js#L1
[2]: https://github.com/nock/nock/blob/de0cb79c9fa4935dc659cf7162ebff549f0e329d/lib/intercept.js

**Comment by quarterto** [comment]
just found https://github.com/RuntimeTools/appmetrics which does a _lot_ more than just http, but it does do http

**Comment by maxcbc** [comment]
#shameless-plug https://medium.com/@maxcbc/outbound-http-s-logging-in-node-js-80572ca3929a

**Comment by rowanmanning** [comment]
We're not gonna get to this before deprecating this system
