### ISSUE TITLE
Why is services.js hard-coded in this component 

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/next-metrics#293]
Move it to next service registry, or make anything that uses n-metrics set their own service meta data  ..?

Granted, not all things that use n-metrics are also in the next-service-registry, but I'm too lazy to update this component every time I need to configure some metric thing

**Comment by umbobabo** [comment]
100% agreed with @adambraimbridge . First time I saw that hardcoded list I was puzzled.
I think we should keep here what is not in next-service-registry but merge the value whit the next-service-registry.json information.

In the next-service-registry we should probably just have a boolean `metric: false` by default for every app that you can then opt-in.

**Comment by rowanmanning** [comment]
We're going to remove this fully and just allow metrics for any service. Will be done soon 👍
