### ISSUE TITLE
Also log method in fetch calls

### ISSUE THREAD

**Issue by maxcbc** [Financial-Times/next-metrics#304]
In here https://github.com/Financial-Times/next-metrics/blob/master/lib/metrics/fetch.js we don't log the method of the request. This would be a nice feature. However:
- just adding it to the existing instrumentation will break existing dashboards 🤢 
- adding it as extra instrumentation will double the about of metrics 🤢 🤢 🤢 

So we should do this the next time we make a breaking change to this instrumentation

**Comment by rowanmanning** [comment]
We're not gonna get to this before deprecating this system
