### ISSUE TITLE
Missing Metrics Healthcheck

### ISSUE THREAD

**Issue by adgad** [Financial-Times/next-metrics#307]
I understand the reason we have the missing metrics healthcheck is because it's better to have the data there when something does go wrong and you need to debug.

_But_ it is awfully painful to have to add a regex for everything (even hackathon things), not to mention slow. Arguably it shouldn't be a healthcheck anyway (and should be a PR review/github issue thing maybe).

BUT what if:
a) we had a catch-all regex (or maybe multiple, like #43 for heroku/api.ft.com/whatever)
b) Rather than a healthcheck on every app, have a single grafana healthcheck or something that tells us when the number of catch-alls is really high. This is making the assumption that we only really care about metrics for the high traffic, important things.

**Comment by adgad** [comment]
<img width="962" alt="screen shot 2018-09-26 at 07 43 12" src="https://user-images.githubusercontent.com/1978880/46075670-1ca12700-c183-11e8-98f8-44dbfd033d93.png">

This is the cost of finding a service - which we do on every fetch request.

**Comment by sjparkinson** [comment]
> Arguably it shouldn't be a healthcheck anyway (and should be a PR review/github issue thing maybe).

Yes.

> https://github.com/Financial-Times/next-metrics/issues/307#issuecomment-424672998

Yeah we could/should be a lot more automated. There's got to be more performant ways of doing it too.

I think it made sense at the beginning, and maybe helped us think about if we _should_ be making calls to a service.

**Comment by rowanmanning** [comment]
We'll be removing the regex thing soon and just allowing any service, it's so much unnecessary toil
