### ISSUE TITLE
Difference between multi-region and single-region metric names

### ISSUE THREAD

**Issue by adgad** [Financial-Times/next-metrics#309]
### Problem
Currently our single-region applications have metric names like `web_1`, and our multiregion apps have metrics like `web_1_EU`.

This makes it firstly confusing when making dashboards, and also means we can't do things like have the FT.com Heroku App dashboard work filter by region (because the regular expression doesn't work across different app types).

### Proposal
Keep the region after every metric - even if it's not a multi-region app. So: `web_1` would become `web_1_EU`.

I'm not sure whether this is actually a code thing in next-metrics - or whether it could be solved by setting the `REGION` environment variable on single region apps?

**Comment by rowanmanning** [comment]
We're not gonna get to this before deprecating this system
