### ISSUE TITLE
Put back clock for 'Send metrics to Graphite' test to check logging detail

### ISSUE THREAD

**Issue by fenglish** [Financial-Times/next-metrics#339]
This commit 54bf44c removed sinon `clock`  from `Send metrics to Graphite` test because an error is thrown when `mitm` version was updated .
```
  1 failing

  1) Logging to graphite
       Send metrics to Graphite:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/circleci/project/build/test/unit/client.spec.old.js)
```
https://circleci.com/gh/Financial-Times/next-metrics/2246

Somehow `clock` in the test causes the error. The test needs to check `Logging to graphite`. It is not super important to know what exactly is the log at this point. The `clock` is deleted to solve the error to able to release new version of next-metrics.

However, the time stamp by sinon `clock` in the log in the test is nice to have.
It may be resolved by updating sinon version.

All detail is in this PR => https://github.com/Financial-Times/next-metrics/pull/337.

**Comment by rowanmanning** [comment]
Hiya, we're slowly sunsetting this repo and it's unlikely we'll ever get to this. I'm gonna close as we'll be releasing a drastically new version soon
