### ISSUE TITLE
Set default value to flushEvery property

### ISSUE THREAD

**Issue by juanSanchezAlcala** [Financial-Times/next-metrics#464]
init method should have a minimum default value for 'flushEvery'.
If not it could cause a lot of calls and increasing the memory too much ending in crashing the app and also affecting the services that received the metrics like a DDOS attack. 
So i suggest that 'flushEvery' property will be set to a minimum in case that you do not specify this property, for example 10 seconds .

**Comment by rowanmanning** [comment]
Hiya, we're slowly sunsetting this repo and it's unlikely we'll ever get to this. I'm gonna close as we'll be releasing a drastically new version soon
