### ISSUE TITLE
Move to Circle and use nbt bottle to update version

### ISSUE THREAD

**Issue by adgad** [Financial-Times/next-metrics#56]

**Comment by adambraimbridge** [comment]
I'm working on this one ... 

- added next-metrics to circleci https://circleci.com/gh/Financial-Times/next-metrics/
- seen that builds are erroring, so cloned repo and updated next-build-tools

Todo: Update to ES6
![image](https://cloud.githubusercontent.com/assets/224547/10941817/0063f140-8305-11e5-824d-b56731555233.png)
